apiVersion: apps/v1
kind: Deployment
metadata:
  name: langflow
  labels:
    app: langflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langflow
  template:
    metadata:
      labels:
        app: langflow
    spec:
      containers:
        - name: langflow
          image: ${REGISTRY_HOST}:30500/${BUILT_IMAGE}
          imagePullPolicy: Always
          ports:
            - containerPort: 7860
          envFrom:
            - configMapRef:
                name: langflow-config
            - secretRef:
                name: langflow-secret
          env:
            - name: POSTGRES_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: langflow-config
                  key: POSTGRES_DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PORT
            - name: LANGFLOW_DATABASE_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB_NAME)"
          startupProbe:
            tcpSocket:
              port: 7860
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 30
          readinessProbe:
            tcpSocket:
              port: 7860
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 7860
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: tis-components
              mountPath: /app/tis_components
            - name: flows-data
              mountPath: /app/flows
            - name: logs-data
              mountPath: /app/logs
            - name: init-scripts-python
              mountPath: /app/init/python

      volumes:
        - name: tis-components
          hostPath:
            path: /workspace/kubernetes/langflow/src/tis_components/
            type: Directory
        - name: flows-data
          persistentVolumeClaim:
            claimName: langflow-flows-pvc
        - name: logs-data
          persistentVolumeClaim:
            claimName: langflow-logs-pvc
        - name: init-scripts-python
          hostPath:
            path: /workspace/kubernetes/langflow/init/python/
            type: Directory