apiVersion: v1
kind: ServiceAccount
metadata:
  name: benchmark-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: benchmark-role
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "patch"] # patch is needed for rollout restart
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: benchmark-rb
subjects:
  - kind: ServiceAccount
    name: benchmark-sa
roleRef:
  kind: Role
  name: benchmark-role
  apiGroup: rbac.authorization.k8s.io
