apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
data:
  AWS_ECR_REGISTRY_URL: "548858542119.dkr.ecr.eu-central-1.amazonaws.com"
  AWS_DEFAULT_REGION: "eu-central-1"
  IMG_PREFIX: "tis"
  ENV_TAG: "prd"
  BITBUCKET_BRANCH: "master"