apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: default
spec:
  limits:
  - default:
      memory: 3Gi
      cpu: 1500m
    defaultRequest:
      memory: 2Gi
      cpu: 500m
    type: Container
