apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
data:
  init-db.sh: |
    #!/bin/bash
    set -e
    export PGPASSWORD="$POSTGRES_PASSWORD"
    DATABASES="langflow_db app_db keycloak_db langfuse_db"
    echo "========================================================================"
    echo "=> Starting database initialization..."
    echo "========================================================================"
    for db in $DATABASES; do
        echo "   -> Checking/Creating database: $db"
        psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "postgres" <<-EOSQL
            SELECT 'CREATE DATABASE "$db"'
            WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$db')\gexec
    EOSQL
    done
    echo "========================================================================"
    echo "=> Database initialization complete."
    echo "========================================================================"
