apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-build
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:latest
          workingDir: /workspace
          env:
            - name: POSTGRES_BUILT_IMAGE
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_BUILT_IMAGE
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PORT
            - name: REGISTRY_URL
              value: "registry.default.svc.cluster.local:5000"
          args:
            - "--dockerfile=kubernetes/postgres/docker/Dockerfile"
            - "--context=/workspace"
            - "--destination=$(REGISTRY_URL)/$(POSTGRES_BUILT_IMAGE)"
            - "--build-arg=POSTGRES_PORT=$(POSTGRES_PORT)"
            - "--build-arg=IMAGE_FROM_REGISTRY=$(REGISTRY_URL)/$(POSTGRES_BUILT_IMAGE)"
            - "--insecure"
            - "--skip-tls-verify"
          volumeMounts:
            - name: workspace
              mountPath: /workspace
      restartPolicy: Never
      volumes:
        - name: workspace
          hostPath:
            path: /workspace
            type: Directory
